title: Kyle Manning # your name (or website title) here
logo: "/images/profile_better.jpeg?raw=true"
# logo: "/images/IMG_3221.jpeg?raw=true"
# description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Senior at Rice University studying Statistics and Economics.
  <br><br>
  Currently working as an intern at OpenStax Research.
  <br><br>
  <a href="https://www.linkedin.com/in/manningkyle/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
